# 🚀 Netlify Configuration for GenLunaMedChain Frontend
# This file configures automatic deployment to Netlify

[build]
  # Build command - includes optional dependencies for esbuild
  command = "npm install --include=optional --legacy-peer-deps && npm run build"
  
  # Directory to publish
  publish = "dist"
  
  # Functions directory (if using Netlify Functions)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Force npm instead of yarn
  NETLIFY_USE_YARN = "false"
  
  # Skip preflight checks
  SKIP_PREFLIGHT_CHECK = "true"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific builds
[context.production]
  command = "npm install --include=optional --legacy-peer-deps && npm run build"
  [context.production.environment]
    VITE_NODE_ENV = "production"

[context.deploy-preview]
  command = "npm install --include=optional --legacy-peer-deps && npm run build"
  [context.deploy-preview.environment]
    VITE_NODE_ENV = "preview"